name: Publish
on: [push]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    if: ${{ github.repository_owner == 'Lepinoid' }}
    uses: Lepinoid/WorkflowCollections/.github/workflows/publish_to_maven-repo.yml@main
    with:
      java_version: 18
      secrets: inherit